### ISSUE TITLE
Bump eslint dependencies to 6.x.x

### ISSUE THREAD

**Issue by pokornyd** [kontent-ai/eslint-config#4]
### Motivation

Package has following dependencies:

[@typescript/eslint-plugin
](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin) ^5.0.0

[@typescript/eslint-parser](https://www.npmjs.com/package/@typescript-eslint/parser) ^5.5.0

For both, a major v6 version was released. Neither of the packages or its dependents can be updated in projects targeting this package until its dependencies are updated.

### Proposed solution

Update eslint dependencies, adjust as required.

**Comment by JiriLojda** [comment]
@pokornyd Fixed with the version 1.0.0 https://www.npmjs.com/package/@kontent-ai/eslint-config
